-- CREATING THE DATABASE
CREATE DATABASE nodebd;

use nodedb;

-- CREATING A TABLE
CREATE TABLE customer (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(50) NOT NULL,
    phone VARCHAR(15)
);

-- SHOW ALL TABLES
SHOW TABLES;

-- TO DESCRIBE THE TABLE
describe customers;